// <auto-generated />
using System;
using BarDG.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarDG.Repository.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("BarDG.Domain.Entity.Comanda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("BarDG.Domain.Entity.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ComandaId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NotaFiscalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProdutoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("BarDG.Domain.Entity.NotaFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotaFiscals");
                });

            modelBuilder.Entity("BarDG.Domain.Entity.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7faccc66-7825-4955-be38-55bc60442b2d"),
                            Descricao = "Cerveja",
                            Valor = 5m
                        },
                        new
                        {
                            Id = new Guid("a8a7133f-399e-4726-af44-90b94fd8853e"),
                            Descricao = "Conhaque",
                            Valor = 20m
                        },
                        new
                        {
                            Id = new Guid("837596d0-d7a4-46b5-ba31-290898fe2ee4"),
                            Descricao = "Suco",
                            Valor = 50m
                        },
                        new
                        {
                            Id = new Guid("d3571a5d-79fd-4beb-9968-35ec551ec435"),
                            Descricao = "Água",
                            Valor = 70m
                        });
                });

            modelBuilder.Entity("BarDG.Domain.Entity.Item", b =>
                {
                    b.HasOne("BarDG.Domain.Entity.Comanda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("ComandaId");

                    b.HasOne("BarDG.Domain.Entity.NotaFiscal", null)
                        .WithMany("Items")
                        .HasForeignKey("NotaFiscalId");

                    b.HasOne("BarDG.Domain.Entity.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId");
                });
#pragma warning restore 612, 618
        }
    }
}
